name = "saisfi-submit-worker"
main = "src/index.ts"
compatibility_date = "2024-09-01"

[vars]
# SUPABASE_URL = "https://your-project.supabase.co"
# TURNSTILE_VERIFY_URL = "https://challenges.cloudflare.com/turnstile/v0/siteverify"

# Cloudflare KV for rate limiting per IP & Form
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "34f6f69b2b60489fb629f1c09c6166e7"
preview_id = "saisfi_ratelimit_kv_preview"
